// docs/ui-design/chat-right-sidebar.tsx
"use client";

import * as React from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Checkbox } from "@/components/ui/checkbox";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  ChevronDownIcon,
  ChevronRightIcon,
  FileTextIcon,
  FileCodeIcon,
  FileJsonIcon,
  ImageIcon,
  FolderIcon,
  FolderOpenIcon,
  InfoIcon,
} from "lucide-react";

interface RightSidebarProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

interface TodoItem {
  id: string;
  text: string;
  completed: boolean;
}

interface FileItem {
  id: string;
  name: string;
  type: "file" | "folder";
  extension?: string;
  children?: FileItem[];
}

const todoItems: TodoItem[] = [
  { id: "1", text: "搜索并整理AI新闻", completed: true },
  { id: "2", text: "生成新闻摘要", completed: true },
  { id: "3", text: "提取趋势洞察", completed: true },
  { id: "4", text: "保存至Markdown文件", completed: true },
  { id: "5", text: "设置自动化推送", completed: false },
];

const files: FileItem[] = [
  {
    id: "1",
    name: "outputs",
    type: "folder",
    children: [
      { id: "1-1", name: "AI_news_20260412.md", type: "file", extension: "md" },
      { id: "1-2", name: "AI_news_20260411.md", type: "file", extension: "md" },
      { id: "1-3", name: "AI_news_20260410.md", type: "file", extension: "md" },
    ],
  },
  {
    id: "2",
    name: "config",
    type: "folder",
    children: [
      { id: "2-1", name: "sources.json", type: "file", extension: "json" },
      { id: "2-2", name: "settings.json", type: "file", extension: "json" },
    ],
  },
  { id: "3", name: "README.md", type: "file", extension: "md" },
  { id: "4", name: "automation.py", type: "file", extension: "py" },
];

export function RightSidebar({ open, onOpenChange }: RightSidebarProps) {
  const [todos, setTodos] = React.useState(todoItems);

  const completedCount = todos.filter((t) => t.completed).length;
  const totalCount = todos.length;
  const progress = (completedCount / totalCount) * 100;

  const toggleTodo = (id: string) => {
    setTodos((prev) =>
      prev.map((todo) =>
        todo.id === id ? { ...todo, completed: !todo.completed } : todo,
      ),
    );
  };

  return (
    <div
      className={cn(
        "flex h-full flex-col border-l border-border bg-sidebar transition-all duration-300",
        open ? "w-72" : "w-0 overflow-hidden",
      )}
    >
      {/* Header */}
      {/* <div className="flex items-center justify-between border-b border-border px-4 py-3">
        <span className="text-sm font-medium"></span>
        <Button
          variant="ghost"
          size="icon"
          className="size-6"
          onClick={() => onOpenChange(false)}
        >
          <XIcon className="size-4" />
        </Button>
      </div> */}

      <Tabs defaultValue="summary" className="flex flex-1 flex-col">
        <TabsList variant="line" className="mx-3 mt-2 w-auto">
          <TabsTrigger value="summary" className="gap-1.5 text-xs">
            <InfoIcon className="size-3.5" />
            概要
          </TabsTrigger>
          <TabsTrigger value="files" className="gap-1.5 text-xs">
            <FolderOpenIcon className="size-3.5" />
            文件
            <span className="ml-1 rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">
              {countFiles(files)}
            </span>
          </TabsTrigger>
        </TabsList>

        <TabsContent value="summary" className="mt-0 flex-1">
          <ScrollArea className="h-full">
            <div className="space-y-4 p-3">
              {/* Session Info */}
              <div className="space-y-2">
                <h4 className="text-xs font-medium text-muted-foreground">
                  会话信息
                </h4>
                <div className="space-y-1.5 rounded-lg bg-muted/50 p-3 text-sm">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">创建时间</span>
                    <span>2026/04/12 09:30</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">消息数量</span>
                    <span>12 条</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Token 用量</span>
                    <span>49k</span>
                  </div>
                </div>
              </div>

              {/* TODO Progress */}
              <div className="space-y-2">
                <h4 className="text-xs font-medium text-muted-foreground">
                  任务进度 ({completedCount}/{totalCount})
                </h4>
                <div className="space-y-2 rounded-lg bg-muted/50 p-3">
                  <div className="flex items-center justify-between text-xs">
                    <span className="text-muted-foreground">完成进度</span>
                    <span className="font-medium">{Math.round(progress)}%</span>
                  </div>
                  <Progress value={progress} className="h-2" />
                </div>

                {/* Todo List */}
                <div className="space-y-1">
                  {todos.map((todo) => (
                    <div
                      key={todo.id}
                      className="flex items-center gap-2 rounded-md px-2 py-1.5 hover:bg-accent"
                    >
                      <Checkbox
                        checked={todo.completed}
                        onCheckedChange={() => toggleTodo(todo.id)}
                        className="size-4"
                      />
                      <span
                        className={cn(
                          "text-sm",
                          todo.completed &&
                            "text-muted-foreground line-through",
                        )}
                      >
                        {todo.text}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="files" className="mt-0 flex-1">
          <ScrollArea className="h-full">
            <div className="p-3">
              <FileTree items={files} />
            </div>
          </ScrollArea>
        </TabsContent>
      </Tabs>
    </div>
  );
}

function FileTree({ items, level = 0 }: { items: FileItem[]; level?: number }) {
  return (
    <div className="space-y-0.5">
      {items.map((item) => (
        <FileTreeItem key={item.id} item={item} level={level} />
      ))}
    </div>
  );
}

function FileTreeItem({ item, level }: { item: FileItem; level: number }) {
  const [isOpen, setIsOpen] = React.useState(true);

  const getFileIcon = (extension?: string) => {
    switch (extension) {
      case "md":
        return <FileTextIcon className="size-4 text-blue-500" />;
      case "json":
        return <FileJsonIcon className="size-4 text-yellow-500" />;
      case "py":
      case "js":
      case "ts":
        return <FileCodeIcon className="size-4 text-green-500" />;
      case "png":
      case "jpg":
      case "svg":
        return <ImageIcon className="size-4 text-purple-500" />;
      default:
        return <FileTextIcon className="size-4 text-muted-foreground" />;
    }
  };

  if (item.type === "folder") {
    return (
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <Button
            variant="ghost"
            className="w-full justify-start gap-1 px-2 py-1 text-sm font-normal"
            style={{ paddingLeft: `${level * 12 + 8}px` }}
          >
            {isOpen ? (
              <ChevronDownIcon className="size-3" />
            ) : (
              <ChevronRightIcon className="size-3" />
            )}
            <FolderIcon className="size-4 text-amber-500" />
            <span className="truncate">{item.name}</span>
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          {item.children && (
            <FileTree items={item.children} level={level + 1} />
          )}
        </CollapsibleContent>
      </Collapsible>
    );
  }

  return (
    <Button
      variant="ghost"
      className="w-full justify-start gap-2 px-2 py-1 text-sm font-normal"
      style={{ paddingLeft: `${level * 12 + 24}px` }}
    >
      {getFileIcon(item.extension)}
      <span className="truncate">{item.name}</span>
    </Button>
  );
}

function countFiles(items: FileItem[]): number {
  return items.reduce((count, item) => {
    if (item.type === "folder" && item.children) {
      return count + countFiles(item.children);
    }
    return count + 1;
  }, 0);
}

// app/work/src/renderer/src/pages/chat/components/ChatRightSidebar.vue
<script setup lang="ts">
import type { Session, TodoItem, Workspace } from "@shared/api";
import { Button } from "@willow/shadcn/components/ui/button";
import { Label } from "@willow/shadcn/components/ui/label";
import { Progress } from "@willow/shadcn/components/ui/progress";
import { ScrollArea } from "@willow/shadcn/components/ui/scroll-area";
import { Separator } from "@willow/shadcn/components/ui/separator";
import { Sidebar } from "@willow/shadcn/components/ui/sidebar";
import { Textarea } from "@willow/shadcn/components/ui/textarea";
import {
  CheckCircle2Icon,
  CircleIcon,
  FolderOpen,
  FileText,
  FolderOpenIcon,
  InfoIcon,
  LoaderIcon,
  Save,
  Settings2Icon,
  XCircleIcon,
} from "lucide-vue-next";
import { computed, ref, toRef, watch } from "vue";
import { useWorkspaceFiles } from "@/composables/useWorkspaceFiles";
import { useWorkspaceSettings } from "@/composables/useWorkspaceSettings";
import { electronAPI } from "@/lib/ipc";
import WorkspaceFileTree from "@/pages/chat/session/components/WorkspaceFileTree.vue";
import { useWorkspaceStore } from "@/stores/workspace";

const props = withDefaults(
  defineProps<{
    mode: "workspace" | "session";
    open: boolean;
    session?: Session;
    workspace?: Workspace;
    messageCount?: number;
    todos?: TodoItem[];
  }>(),
  {
    messageCount: 0,
    todos: () => [],
  },
);

const workspaceStore = useWorkspaceStore();
const widthClass = computed(() => {
  if (props.open) {
    return "w-80 basis-80";
  }
  return "w-0 basis-0";
});
const workspaceId = computed(() => props.workspace?.id ?? props.session?.workspaceId ?? 0);
const activeTab = ref<"primary" | "files">(props.mode === "workspace" ? "primary" : "primary");
const {
  files,
  rootPath,
  isLoading: isFilesLoading,
  errorMessage: filesErrorMessage,
} = useWorkspaceFiles(workspaceId);
const {
  workspacePath,
  soulContent,
  isLoading: isSettingsLoading,
  isSaving,
  errorMessage: settingsErrorMessage,
  saveMessage,
  saveSettings,
} = useWorkspaceSettings(toRef(workspaceId));

const completedCount = computed(
  () => props.todos.filter((todo) => todo.status === "completed").length,
);
const totalCount = computed(() => props.todos.length);
const progress = computed(() => {
  if (!totalCount.value) {
    return 0;
  }
  return (completedCount.value / totalCount.value) * 100;
});
const formattedCreatedAt = computed(() => {
  if (!props.session?.createdAt) {
    return "--";
  }
  return new Intl.DateTimeFormat("zh-CN", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(props.session.createdAt));
});
const formattedUpdatedAt = computed(() => {
  if (!props.session?.lastActiveAt) {
    return "--";
  }
  return new Intl.DateTimeFormat("zh-CN", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(props.session.lastActiveAt));
});
const totalFileCount = computed(() => countFiles(files.value));
const primaryTabLabel = computed(() => (props.mode === "workspace" ? "设置" : "概要"));
const primaryTabIcon = computed(() => (props.mode === "workspace" ? Settings2Icon : InfoIcon));
const hasValidWorkspace = computed(() => workspaceId.value > 0 && !Number.isNaN(workspaceId.value));

const statusConfig = {
  completed: { icon: CheckCircle2Icon, className: "text-emerald-500" },
  in_progress: { icon: LoaderIcon, className: "text-blue-500 animate-spin" },
  pending: { icon: CircleIcon, className: "text-muted-foreground/60" },
  cancelled: { icon: XCircleIcon, className: "text-destructive/60" },
} as const;

watch(
  () => props.mode,
  (mode) => {
    activeTab.value = "primary";
  },
);

function countFiles(items: typeof files.value): number {
  return items.reduce((count, item) => {
    if (item.type === "folder" && item.children) {
      return count + countFiles(item.children);
    }
    return count + (item.type === "file" ? 1 : 0);
  }, 0);
}

async function handleSaveWorkspaceSettings() {
  await saveSettings();
  await workspaceStore.fetchWorkspaceList();
}

async function handleOpenWorkspaceFolder() {
  const path = rootPath.value || props.workspace?.path || workspacePath.value;
  if (!path) {
    return;
  }

  await electronAPI.openPath({ path });
}
</script>

<template>
  <aside
    class="min-h-0 flex-none overflow-hidden transition-[width,flex-basis] duration-300 ease-in-out"
    :class="widthClass"
  >
    <Sidebar
      side="right"
      collapsible="none"
      class="h-full w-80 border-l border-border bg-card"
      :style="{ '--sidebar-width': props.open ? '20rem' : '0rem' }"
    >
      <div class="flex h-full flex-col">
        <div class="border-b border-sidebar-border px-3 py-2">
          <div class="flex items-center gap-1">
            <Button
              type="button"
              variant="ghost"
              size="sm"
              class="h-8 gap-1.5 px-2 text-xs"
              :class="
                activeTab === 'primary' ? 'bg-muted text-foreground' : 'text-muted-foreground'
              "
              @click="activeTab = 'primary'"
            >
              <component :is="primaryTabIcon" class="size-3.5" />
              {{ primaryTabLabel }}
            </Button>
            <Button
              type="button"
              variant="ghost"
              size="sm"
              class="h-8 gap-1.5 px-2 text-xs"
              :class="activeTab === 'files' ? 'bg-muted text-foreground' : 'text-muted-foreground'"
              @click="activeTab = 'files'"
            >
              <FolderOpenIcon class="size-3.5" />
              文件
              <span class="rounded bg-background px-1.5 py-0.5 text-[10px] text-muted-foreground">
                {{ totalFileCount }}
              </span>
            </Button>
          </div>
        </div>

        <ScrollArea v-if="activeTab === 'primary'" class="h-full">
          <div v-if="props.mode === 'workspace'" class="space-y-6 p-4">
            <div class="space-y-2">
              <h4 class="text-xs font-medium text-muted-foreground">工作空间信息</h4>
              <div class="space-y-1.5 rounded-lg bg-muted/50 p-3 text-sm">
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">名称</span>
                  <span class="truncate text-right">{{
                    props.workspace?.name || "未命名工作空间"
                  }}</span>
                </div>
              </div>
            </div>

            <Separator />

            <div class="space-y-3">
              <div class="flex items-center gap-2 text-sm font-medium text-foreground">
                <FileText class="h-4 w-4" />
                <span>soul.md 设置</span>
              </div>
              <div class="space-y-2">
                <Label for="workspace-soul-content" class="text-xs text-muted-foreground">
                  定义 AI 助手的行为和人格特征
                </Label>
                <Textarea
                  id="workspace-soul-content"
                  v-model="soulContent"
                  placeholder="# AI 助手配置&#10;&#10;描述你希望 AI 助手具有的特性..."
                  class="min-h-[240px] resize-none font-mono text-sm"
                />
                <p class="text-xs text-muted-foreground">
                  支持 Markdown 格式，保存到工作空间的 soul.md
                </p>
              </div>
            </div>

            <div v-if="settingsErrorMessage" class="text-xs text-destructive">
              {{ settingsErrorMessage }}
            </div>
            <div v-else-if="saveMessage" class="text-xs text-emerald-600">
              {{ saveMessage }}
            </div>

            <Button class="w-full gap-2" :disabled="isSaving" @click="handleSaveWorkspaceSettings">
              <Save class="h-4 w-4" />
              {{ isSaving ? "保存中..." : "保存设置" }}
            </Button>
          </div>

          <div v-else class="space-y-4 p-3">
            <div class="space-y-2">
              <h4 class="text-xs font-medium text-muted-foreground">会话信息</h4>
              <div class="space-y-1.5 rounded-lg bg-muted/50 p-3 text-sm">
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">标题</span>
                  <span class="truncate text-right">{{
                    props.session?.title || "未命名会话"
                  }}</span>
                </div>
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">创建时间</span>
                  <span class="text-right">{{ formattedCreatedAt }}</span>
                </div>
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">最近活跃</span>
                  <span class="text-right">{{ formattedUpdatedAt }}</span>
                </div>
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">消息数量</span>
                  <span class="text-right">{{ props.messageCount }} 条</span>
                </div>
                <div class="flex justify-between gap-3">
                  <span class="text-muted-foreground">工作空间</span>
                  <span class="truncate text-right">{{ props.workspace?.name || "--" }}</span>
                </div>
              </div>
            </div>

            <div v-if="props.todos.length > 0" class="space-y-2">
              <Separator />
              <h4 class="text-xs font-medium text-muted-foreground">
                任务进度 ({{ completedCount }}/{{ totalCount }})
              </h4>
              <div class="space-y-2 rounded-lg bg-muted/50 p-3">
                <div class="flex items-center justify-between text-xs">
                  <span class="text-muted-foreground">完成进度</span>
                  <span class="font-medium">{{ Math.round(progress) }}%</span>
                </div>
                <Progress :model-value="progress" class="h-2" />
              </div>

              <div class="space-y-1">
                <div
                  v-for="todo in props.todos"
                  :key="todo.id"
                  class="flex items-start gap-2 rounded-md px-2 py-1.5 text-sm hover:bg-accent/60"
                >
                  <component
                    :is="statusConfig[todo.status].icon"
                    class="mt-0.5 size-4 shrink-0"
                    :class="statusConfig[todo.status].className"
                  />
                  <span
                    :class="{
                      'text-muted-foreground line-through':
                        todo.status === 'completed' || todo.status === 'cancelled',
                      'font-medium': todo.status === 'in_progress',
                    }"
                  >
                    {{ todo.content }}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </ScrollArea>

        <ScrollArea v-else class="h-full">
          <div class="space-y-3 p-3">
            <div class="space-y-1">
              <div class="text-xs font-medium text-muted-foreground">工作空间文件</div>
              <div class="flex items-center gap-2">
                <div class="min-w-0 flex-1 truncate text-xs text-muted-foreground">
                  {{ rootPath || props.workspace?.path || "未找到工作空间路径" }}
                </div>
                <Button
                  v-if="rootPath || props.workspace?.path || workspacePath"
                  type="button"
                  variant="ghost"
                  size="icon"
                  class="h-7 w-7 shrink-0"
                  title="打开当前工作空间文件夹"
                  @click="handleOpenWorkspaceFolder"
                >
                  <FolderOpen class="size-4" />
                </Button>
              </div>
            </div>

            <div
              v-if="isFilesLoading"
              class="rounded-lg border border-dashed border-border px-3 py-6 text-center text-sm text-muted-foreground"
            >
              正在读取文件列表...
            </div>
            <div
              v-else-if="filesErrorMessage"
              class="rounded-lg border border-dashed border-destructive/30 px-3 py-6 text-center text-sm text-muted-foreground"
            >
              {{ filesErrorMessage }}
            </div>
            <div
              v-else-if="files.length === 0"
              class="rounded-lg border border-dashed border-border px-3 py-6 text-center text-sm text-muted-foreground"
            >
              当前工作空间没有可展示的文件
            </div>
            <div v-else class="rounded-lg bg-muted/40 p-2">
              <WorkspaceFileTree :items="files" />
            </div>
          </div>
        </ScrollArea>
      </div>
    </Sidebar>
  </aside>
</template>
